name    'puppetmodule-puppetcron'
version '0.0.2'
source  'git@git-infra.internal:puppet/puppetmodule_puppetcron.git'
author  'pcanham'
license ''
summary 'Puppet client cron'
description     'Creates a cron to run the puppet client at a random interval'
project_page    'http://git-infra.internal/puppet/puppetmodule_puppetcron.git'
